# Generated by Django 3.2.16 on 2022-11-02 14:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(150)], verbose_name='age')),
                ('phone', models.BigIntegerField(blank=True, default=0, unique=True, verbose_name='phone')),
                ('care_about', models.ManyToManyField(related_name='_managment_patient_care_about_+', to='managment.Patient', verbose_name='care about')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managment.patient', verbose_name='user')),
            ],
            options={
                'unique_together': {('patient', 'title')},
            },
        ),
        migrations.CreateModel(
            name='ReportDot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(verbose_name='x')),
                ('y', models.FloatField(verbose_name='y')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managment.report', verbose_name='report')),
            ],
        ),
        migrations.CreateModel(
            name='PatientSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('w', 'white'), ('b', 'blue'), ('r', 'red'), ('o', 'orange'), ('g', 'green')], default='white', max_length=255, verbose_name='color')),
                ('font', models.IntegerField(verbose_name='font')),
                ('city', models.CharField(max_length=255, verbose_name='city')),
                ('language', models.CharField(choices=[('RU', 'RUSSIAN'), ('EN', 'ENGLISH')], max_length=255, verbose_name='language')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='managment.patient', verbose_name='patient')),
            ],
        ),
    ]
