# Generated by Django 3.2.16 on 2022-12-14 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='banned',
            field=models.BooleanField(blank=True, help_text='Был ли он забанен опекуном через администратора', null=True, verbose_name='banned'),
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='care_about',
        ),
        migrations.AddField(
            model_name='guardian',
            name='care_about',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='managment.patient', verbose_name='care about'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='is_send',
            field=models.BooleanField(blank=True, help_text='отправлять ли отчеты об опекуне', null=True, verbose_name='is_send'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='relationship',
            field=models.CharField(blank=True, help_text='родство с опекуном', max_length=150, null=True, verbose_name='relationship'),
        ),
    ]
