# Generated by Django 3.2.16 on 2022-11-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='care_about',
            field=models.ManyToManyField(blank=True, null=True, related_name='_managment_patient_care_about_+', to='managment.Patient', verbose_name='care about'),
        ),
    ]
