# Generated by Django 3.2.16 on 2022-12-16 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0002_auto_20221214_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardian',
            name='email',
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='is_active',
        ),
    ]
