# Generated by Django 4.1.1 on 2022-12-17 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0002_doctor_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorvisit',
            name='user',
        ),
        migrations.AddField(
            model_name='doctorvisit',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='managment.patient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctorvisit',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managment.doctor'),
        ),
    ]
