# Generated by Django 4.1.1 on 2022-12-18 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0003_remove_doctorvisit_user_doctorvisit_patient_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='doctorvisit',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='guardian',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ('id',)},
        ),
    ]
