# Generated by Django 3.2.16 on 2022-12-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0003_auto_20221216_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='is_send',
            field=models.BooleanField(blank=True, default=False, help_text='отправлять ли отчеты об опекуне', null=True, verbose_name='is_send'),
        ),
    ]
