# Generated by Django 3.2.16 on 2022-11-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0004_doctor_doctorvisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(blank=True, choices=[('эндокринолог', 'эндокринолог'), ('невролог', 'невролог'), ('терапевт', 'терапевт'), ('кардиолог', 'кардиолог'), ('окулист', 'окулист'), ('диетолог', 'диетолог'), ('хирург', 'хирург')], max_length=150, verbose_name='specialty'),
        ),
    ]
