# Generated by Django 3.2.16 on 2022-11-30 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0005_alter_doctor_specialty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='user',
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
        migrations.DeleteModel(
            name='Label',
        ),
    ]
