# Generated by Django 3.2.16 on 2022-12-11 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicine', '0001_initial'),
        ('managment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managment.patient', verbose_name='user')),
            ],
            options={
                'unique_together': {('patient', 'title')},
            },
        ),
        migrations.CreateModel(
            name='TakenMed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('is_late', models.BooleanField(max_length=255, verbose_name='is_late')),
                ('report', models.BooleanField(help_text='был ли включен в отчет', max_length=255, verbose_name='report')),
                ('med', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.cure')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managment.patient', verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='ReportDot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(help_text='колво принятых', verbose_name='x')),
                ('y', models.FloatField(help_text='колво не принятых', verbose_name='y')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managment.patient', verbose_name='user')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistic.report', verbose_name='report')),
            ],
        ),
        migrations.CreateModel(
            name='MissedMed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('is_informed', models.BooleanField(help_text='is informed guardian', max_length=255, verbose_name='is_informed')),
                ('med', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.cure')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managment.patient', verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='action')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managment.patient', verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('user', models.ManyToManyField(to='managment.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Devise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api', models.CharField(max_length=255, verbose_name='api')),
                ('type_of_devise', models.CharField(choices=[('tablet', 'tablet'), ('phone', 'phone'), ('notebook', 'notebook'), ('desktop', 'desktop')], max_length=255, verbose_name='type_of_devise')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managment.patient', verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_attended', models.PositiveIntegerField(verbose_name='days_attended')),
                ('days_no_miss', models.PositiveIntegerField(verbose_name='days_no_miss')),
                ('number_in_time', models.PositiveIntegerField(verbose_name='number_in_time')),
                ('praise_from_guard', models.PositiveIntegerField(help_text='количество раз похвалы', verbose_name='praise_from_guard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managment.patient')),
            ],
        ),
    ]
