# Generated by Django 4.1.1 on 2022-12-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takenmed',
            name='is_late',
            field=models.BooleanField(verbose_name='is_late'),
        ),
        migrations.AlterField(
            model_name='takenmed',
            name='report',
            field=models.BooleanField(help_text='был ли включен в отчет', verbose_name='report'),
        ),
    ]
