# Generated by Django 3.2.16 on 2022-11-30 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0006_auto_20221130_1203'),
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('user', models.ManyToManyField(to='managment.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_attended', models.PositiveIntegerField(verbose_name='days_attended')),
                ('days_no_miss', models.PositiveIntegerField(verbose_name='days_no_miss')),
                ('number_in_time', models.PositiveIntegerField(verbose_name='number_in_time')),
                ('praise_from_guard', models.PositiveIntegerField(help_text='количество раз похвалы', verbose_name='praise_from_guard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managment.patient')),
            ],
        ),
    ]
