# Generated by Django 4.1.1 on 2022-12-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0002_alter_takenmed_is_late_alter_takenmed_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missedmed',
            name='is_informed',
            field=models.BooleanField(help_text='is informed guardian', verbose_name='is_informed'),
        ),
    ]
