# Generated by Django 3.2.16 on 2022-11-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='strict_status',
            field=models.BooleanField(max_length=255, verbose_name='strict'),
        ),
    ]
