# Generated by Django 4.1.1 on 2022-12-18 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cure',
            options={'ordering': ('id',)},
        ),
    ]
