# Generated by Django 3.2.16 on 2022-12-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='strict_status',
        ),
        migrations.AddField(
            model_name='cure',
            name='food',
            field=models.CharField(choices=[('Before meals', 'Before meals'), ('While eating', 'While eating'), ('After meal', 'After meal'), ('No matter', 'No matter')], max_length=255, null=True, verbose_name='food'),
        ),
        migrations.AddField(
            model_name='cure',
            name='strict_status',
            field=models.BooleanField(default=False, max_length=255, null=True, verbose_name='strict'),
        ),
    ]
