# Generated by Django 3.2.16 on 2022-11-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_auto_20221128_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cure',
            name='type',
            field=models.CharField(choices=[('УКОЛ', 'УКОЛ'), ('АМПУЛА', 'АМПУЛА'), ('ТАБЛЕТКА', 'ТАБЛЕТКА'), ('СУСПЕНЗИЯ', 'СУСПЕНЗИЯ')], max_length=255, verbose_name='type'),
        ),
    ]
